name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the script
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: kotlin TES_Turnierplaner/Turnierplaner/app/src/main/java/com/example/turnierplaner/LogInActivity.kt
