name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: kotlinc TES_Turnierplaner/Turnierplaner/app/src/main/java/com/example/turnierplaner/LogInActivity.kt -include-runtime -d /tmp/hello.jar; java -jar /tmp/hello.jar
      - run: kotlin TES_Turnierplaner/Turnierplaner/app/src/main/java/com/example/turnierplaner/LogInActivity.kt
