# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kotlin CI

on:
    push:
    workflow_dispatch:
    pull_request:
    

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x Turnierplaner/build.gradle
            - name: Build with Gradle
              run: Turnierplaner/build.gradle build
