name: Build

on:
    push:
    workflow_dispatch:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x Turnierplaner/gradle/wrapper
            - name: Build with Gradle
              run: Turnierplaner/gradle/wrapper/gradle-wrapper.jar build
